### ISSUE TITLE
로그인 및 회원가입 (메인 페이지 포함)

### ISSUE THREAD

**Issue by Ontheway-01** [TodoChallengers/TodoChallengers-FE#2]
로그인 및 회원가입 페이지 / 메인 페이지 UI 제작
- 토큰 처리 관련해서 공부하기

**TODO**
- [x] 메인 페이지 componenet 제작
- [x] 메인 페이지 제작
- [x] 로그인 및 회원가입 component 제작
- [x] 로그인 페이지 제작
- [x] 회원가입 페이지 제작

**Comment by RumosZin** [comment]
아직 구현 시작하지 않으신 것 같아 지금 관련 이야기 남깁니다.

백엔드에서는 회원가입/로그인 관련해서 카카오 로그인, 일반 회원가입/로그인 작업하기로 했고 Jwt 토큰 방식으로 구현하려 합니다. Jwt를 이용한 카카오 로그인에 대해서는 [여기 블로그](https://velog.io/@jiwoow00/Spring-boot-JWT-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%B0%B1%EC%97%94%EB%93%9C-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8)에서 잘 설명하고 있으니 확인해보시면 좋을 것 같습니다!
